server:
  port: 9090
  servlet:    context-path: /my-contact-app
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: tiger
    driver-class-name: oracle.jdbc.OracleDriver